upstream laravel_backend {
    # least_conn; # send new requests to the least connection server
    # ip_hash; # send new requests with ip address to the same ip address ex: requests from Egypt go to the server located in Egypt
    # weight=3 for more powerful server to take more traffic
    # max_fails=3 remove from cluster if fails 3 times
    # fail_timeout=30 stop for 30s if failed
    least_conn;
    server app1:9000 weight=1 max_fails=3 fail_timeout=30s;
    server app2:9000 weight=1 max_fails=3 fail_timeout=30s;
    server app3:9000 backup;
}

server {
    listen 80;
    server_name laravel_docker.app;
    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        # important at heavy traffic
        # fastcgi_read_timeout 300;
        # fastcgi_buffers 16 16k;
        # fastcgi_buffer_size 32k;
    }
}
